import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Portforlio.module.css'


export default function Portfolio() {
    return (
      <>
        <Head>
          <title>AX-Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          
          <meta name="viewport" content="width=device-width, initial-scale=1" />
         
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main >
          
            
              <h1 className={styles.main}>
                Portfolio ++
              </h1>
          
        </main>
      </>
    )
  }
  